### ISSUE TITLE
Update plugin to use Yelp Fusion API

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Yelp-Widget-Premium#30]
## Issue Overview

![image](https://user-images.githubusercontent.com/1938671/34129170-2b52fe22-e411-11e7-86f4-2401bf1a9d26.png)

## Tasks

- [x] Add field for `Yelp Fusion API Key`.
- [x] Update search request to use Fusion API.
- [x] Update business request to use Fusion API.
- [x] Update reviews request to use Fusion API.
- [x] Update all variable names in templates if they have changed.
- [x]  Add star images to plugin since API does not provide them anymore.
- [x] Replace Yelp logo image with transparent PNG
- [x] Update localized JSON data so that locations appear on Google Maps again.
- [x] Update inline docs with instructions to get Fusion API key.

## Related

https://secure.helpscout.net/conversation/480415647/12209/?folderId=672191
